version: "3"

services:
  postgres:
    image: postgres
    container_name: postgres
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: subit_tech_test

  node:
    build:
      context: .
    container_name: node
    restart: unless-stopped
    environment:
      DB_HOST: postgres
    depends_on:
      - postgres
    ports:
      - 9090:9090

networks:
  default:
    name: subit-tech-test

volumes:
  db-data:
